### PR TITLE
Swift 3 Support

### PR DESCRIPTION
**Pull request by ArtSabintsev**
This PR will remain open until Xcode 8.0 GM is released.

 Initial conversion to Swift 3 was done in Xcode 8.0b2.

All work for Swift 3 compatibility will be done in this branch.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Currently, this does not compile, as there is a bug in NSUbiquitousKeyValueStore. I've filed a radar and made a copy in OpenRadar: http://openradar.appspot.com/radar?id=4939607762272256

**Comment by ArtSabintsev** [comment]
Updated for Xcode 8b4.

Meant to say this earlier, but everything works in Swift 3 in both Xcode8b3 and Xcode8b4.

**Comment by ArtSabintsev** [comment]
Thanks, I'll fix it now. `removeObject(forKey:)` didn't work in a previous beta.

**Comment by ArtSabintsev** [comment]
@matej @steipete Fixed. Thanks! 

As I mentioend to @steipete on Twitter, I didn't see any notifications on Github that a comment was left, which is why I never responded.

**Comment by matej** [comment]
@ArtSabintsev ah, sorry. I should have opened an issue instead. Thanks for fixing this.

**Comment by ArtSabintsev** [comment]
My pleasure, @matej!

**Comment by ArtSabintsev** [comment]
Zephyr now works Xcode 8b6. I also nuked most of the sample project, as I got sick of fixing it with every new version of Xcode 8b6. Hopefully, the lib can still be installed using Carthage.

**Comment by ArtSabintsev** [comment]
Merging this to master. Should be available via CocoaPods very soon.

**Comment by ArtSabintsev** [comment]
Merged as version `2.0.0`.

Enjoy!

**Pull request merged**
