### PR TITLE
Set minimum required swift version to 5.0

### PR DESCRIPTION
**Pull request by funkenstrahlen**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
I thought 4.0 was the latest. When did 5.0 become the latest version of the spec?

**Comment by funkenstrahlen** [comment]
This setting describes the minimum swift version required to build the package. As you updated the code to Swift 5 this should be changed I think.

**Comment by ArtSabintsev** [comment]
Do you have a link for that? I had an issue finding it before

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
Found it: https://developer.apple.com/documentation/swift_packages/package

Thanks! Need to change it on a lot of libs now.

**Pull request merged**
