### PR TITLE
update to latest swift 3 changes that came with Xcode 8 beta 6

### PR DESCRIPTION
**Pull request by michaelochs**
this PR updates Zephyr.swift so that it can be compiled with the latest Swift 3 changes that came with the release of Xcode 8 beta 6.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Ah, so they finally implemented the `fileprivate` scope - awesome!

Alright, I'll take a look tonight after work. Thank you!

**Comment by ArtSabintsev** [comment]
Ended up making a couple more tiny changes, so I just pushed directly. Thanks for the PR, thought, and for being so diligent about it!

**Comment by michaelochs** [comment]
Sure, no problem. I tired to only change the minimum set to make it work again :)

**Comment by ArtSabintsev** [comment]
Thanks - I appreciate it. 

Do the changes in https://github.com/ArtSabintsev/Zephyr/pull/10 work for you?

**Pull request closed without merging**
